#
# Makefile for the Cypress touchkey driver
#


#ifeq ($(CONFIG_MACH_U1), y)
#obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += cypress-touchkey_u1.o
#else
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += cypress-touchkey.o
#endif
obj-$(CONFIG_KEYBOARD_CYPRESS_TOUCH) += issp_driver_routines.o issp_main.o issp_routines.o
