#
# Makefile for the sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_SENSORS_SSP_LSM330)	+= accel_lsm330.o gyro_lsm330.o

obj-$(CONFIG_SENSORS_SSP_CM36651)	+= light_cm36651.o prox_cm36651.o

obj-$(CONFIG_SENSORS_SSP_BMP182)	+= pressure_bmp182.o

